<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Execption Handling in Promise</title>
</head>
<body>
	<script type="text/javascript">

		let userAuthorized = false;

		function getUserById(id){
			
			return new Promise((resolve,reject) => {

				if(!userAuthorized){
					throw new Error("User is not Authorized");
				}

				resolve({
					id: id,
					username: 'admin'
				});
			});
		}

		try{
			getUserById(7).then( user => console.log(user.username)).catch(error => console.log( `Caught by .catch` + error ));
		}catch(error){
			console.log( `Caught by try/catch {$error}`);
		}

		
	</script>
</body>
</html>